.TH XSETURGENT 1 xseturgent\-VERSION
.SH NAME
xseturgent \- set an applications urgency hint (or not)
.SH SYNOPSIS
.B xseturgent
.RB <winid>
.RB [0|1]
.SH OPTIONS
.TP
.B <winid>
the window id (decimal or hexadecimal).
.TP
.B [0|1]
0 to unset, 1 to set, if not specified 1 is the default.
.SH DESCRIPTION
xseturgent can set or unset an applications urgency hint
.SH SEE ALSO
.BR xprop(1)
.BR xwininfo(1)
.SH BUGS
Please report them!
