---
name: CI
on: [ workflow_dispatch, push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker://lpenz/omnilint:0.5.1
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker://lpenz/ghaction-cmake:0.22.0
        with:
          dependencies_debian: libx11-dev xvfb xauth xterm
          preset: coverage
      - uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
  tests:
    strategy:
        matrix:
          preset:
            - cppcheck
            - iwyu
            - clang-tidy
            - install
            - clang-sanitize-address
            - clang-sanitize-memory
            - clang-sanitize-undefined
            - clang-sanitize-safe-stack
            - valgrind
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: docker://lpenz/ghaction-cmake:0.22.0
        with:
          dependencies_debian: libx11-dev xvfb xauth xterm
          preset: ${{ matrix.preset }}
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: DoozyX/clang-format-lint-action@v0.14
  publish-packagecloud:
    needs: [ omnilint, clang-format, tests, coverage ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant:
          - image: debian-bullseye-amd64
            distro: debian
            version: bullseye
          - image: debian-bookworm-amd64
            distro: debian
            version: bookworm
          - image: ubuntu-jammy-amd64
            distro: ubuntu
            version: jammy
    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0
      - uses: docker/setup-qemu-action@v2.1.0
      - uses: docker://lpenz/ghaction-cmake:0.22.0
        if: matrix.variant.image == 'debian-bullseye-amd64'
        with:
          preset: cpack
          dependencies_debian: gkrellm libgtk2.0-dev
      - uses: docker://lpenz/ghaction-cmake:0.22.0
        if: matrix.variant.image == 'debian-bookworm-amd64'
        with:
          preset: cpack
          dependencies_debian: gkrellm libgtk2.0-dev
      - uses: docker://lpenz/ghaction-cmake:0.22.0
        if: matrix.variant.image == 'ubuntu-jammy-amd64'
        with:
          preset: cpack
          dependencies_debian: gkrellm libgtk2.0-dev
      - run: |
          for f in *.deb; do ls -l "$f"; dpkg --info "$f"; done
      - id: version
        uses: docker://lpenz/ghaction-version-gen:0.13.5
      - uses: docker://lpenz/ghaction-packagecloud:0.4
        if: steps.version.outputs.version_commit != ''
        with:
          repository: ${{ matrix.variant.distro }}/${{ matrix.variant.distro }}/${{ matrix.variant.version }}
        env:
          PACKAGECLOUD_TOKEN: ${{ secrets.PACKAGECLOUD_TOKEN }}

